// Optional after explicit test permission: node scripts/check-images.ts
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { portraitNames, sceneImage, developmentImages, expressionRules } from '../src/images.ts';
import { currentImageContext, findImage, bounded } from '../src/image-loader.ts';
const portrait = (expression: string, clothing = '女仆服') => portraitNames('noah', { expression, clothing });
assert.deepEqual(portrait('羞涩地微笑', '睡衣'), ['noah__blush_underwear.png', 'noah__default_underwear.png', 'noah__default.png']);
assert.equal(portrait('微怒')[0], 'noah__default.png');
assert.equal(portrait('微笑')[0], 'noah__smile.png');
assert.equal(portrait('不喜欢')[0], 'noah__smile.png'); // Deliberate literal matching, not negation parsing.
assert.equal(portrait('疲惫地微笑')[0], 'noah__tired_smile.png');
assert.equal(portrait('神态平静', '未穿内衣')[0], 'noah__default_underwear.png');
assert.equal(portraitNames('seraphina', { expression: '脸红', clothing: '修女服，戴头纱' })[0], 'seraphina__default_sisterveil.png');
assert.equal(portraitNames('seraphina', { expression: '开心地微笑', clothing: '修女服' })[0], 'seraphina__smile.png');
assert.equal(portraitNames('tanuki', { expression: '忧虑', clothing: '睡衣' })[0], 'tanuki__worried.png');
assert.equal(portraitNames('lilicia', { expression: '严令', clothing: '便服' })[0], 'lilicia__command.png');
assert.equal(expressionRules.find(([name]) => name === 'smile')?.[1], '喜欢乐笑');
assert.equal(sceneImage({ day: 1, period: '上午', location: '客厅' }).names[0], 'bg__living_day.png');
assert.match(sceneImage({ day: 1, period: '傍晚', location: '宅邸起居室' }).note, /夜景/);
assert.equal(sceneImage({ day: 1, period: '夜间', location: '瑟雷妮亚' }).names.length, 0);
assert.equal(sceneImage(undefined).names.length, 0);
assert.equal(developmentImages.length, 55);
assert.equal(new Set(developmentImages.map(image => image.name)).size, 55);
for (const image of developmentImages) assert.ok(existsSync(new URL(`../public/${image.source}`, import.meta.url)), image.source);
const item = { character: 'CARD', fileName: 'noah__default.png', relativePath: 'folder/noah__default.png' };
assert.equal(findImage([item], item.fileName), item);
assert.equal(findImage([item], 'tanuki__default.png'), undefined);
assert.throws(() => findImage([item, item], item.fileName), /重名/);
assert.throws(() => findImage([{ ...item, relativePath: '../noah__default.png' }], item.fileName), /路径/);
const host = { SillyTavern: { getContext: () => ({ characterId: 0, groupId: null, getCurrentChatId: () => 'new-chat' }) } } as never;
currentImageContext(host, '[0,"new-chat"]');
assert.throws(() => currentImageContext(host, '[0,"old-chat"]'), /聊天/);
const controller = new AbortController();
controller.abort();
await assert.rejects(bounded(new Promise(() => {}), controller.signal), /取消/);
const loader = readFileSync(new URL('../src/image-loader.ts', import.meta.url), 'utf8');
assert.doesNotMatch(loader, /\.revokeUrl\(|\.clearCache\(|replaceVariables|setChatMessages/);
const imageComponent = readFileSync(new URL('../src/CardImage.vue', import.meta.url), 'utf8');
assert.match(imageComponent, /object-fit: contain/);
assert.match(imageComponent, /onCleanup\(\(\) => controller\.abort\(\)\)/);
console.log('N4 image checks passed; browser/Gremlin/manual acceptance still separate.');
